let  allData = [
  {
  id:1,  photo:"https://trycasuals.com/wp-content/uploads/2018/06/mug-coffee-5-600x600.jpg",
  category:"mugs",
  title:"black printed coffee mug",
   price:100,
  },
  {
   id:2, photo:"https://trycasuals.com/wp-content/uploads/2018/06/mug-coffee-5-600x600.jpg", 
   category:"mugs",
   title:"father day coffee mug",
   price:150,
    },
  {
    id:3,
  photo:"https://trycasuals.com/wp-content/uploads/2018/06/tshirt6-4-600x600.jpg", 
   category:"T-shirts", 
   title:"yellow T-shirt",
   price:200,
      },
  {id:4,        photo:"https://trycasuals.com/wp-content/uploads/2018/06/mug-blue-4-600x600.jpg",
         category:"mugs",
         title:"blue coffee mug",
         price:50,
        },
  {id:5,       photo:"https://trycasuals.com/wp-content/uploads/2018/06/tshirt5-4-600x600.jpg", 
      category:"T-shirts", 
      title:"green T-shirt",
           price:205,
          },
  {id:6,
  photo:"https://trycasuals.com/wp-content/uploads/2018/06/tshirt3-4-600x600.jpg",
     category:"T-shirts",
    title:"pink T-shirt",
             price:759,
            },
  { id:7,photo:"https://trycasuals.com/wp-content/uploads/2018/06/mug-blue-4-600x600.jpg" ,
   category:"mugs",
   title:"blue coffee mug",
   price:500,
              },
  { id:9,
   photo:"https://trycasuals.com/wp-content/uploads/2018/06/mug-coffee-5-600x600.jpg",
   category:"mugs",
   title:"black printed coffee mug",
   price:20,
     },
     ];
export default allData;